### ISSUE TITLE
'vern install' returns TypeError instead of real error

### ISSUE THREAD

**Issue by adepatie** [uh-sem-blee/vern-cli#36]
Just entering 'vern install' returns this error:

    TypeError: Cannot call method 'charAt' of undefined
        at Object.parseInstall [as cb] (/Users/alex.depatie/.nvm/v0.10.33/lib/node_modules/vern-    cli/bin/vern:1416:29)
        at Object.ArgParser.parse (/Users/alex.depatie/.nvm/v0.10.33/lib/node_modules/vern-cli/node_modules/nomnom/nomnom.js:302:15)
        at Object.<anonymous> (/Users/alex.depatie/.nvm/v0.10.33/lib/node_modules/vern-cli/bin/vern:78:9)
        at Module._compile (module.js:456:26)
        at Object.Module._extensions..js (module.js:474:10)
        at Module.load (module.js:356:32)
        at Function.Module._load (module.js:312:12)
        at Function.Module.runMain (module.js:497:10)
        at startup (node.js:119:16)
        at node.js:906:3

This should log the same error as other 'vern install' related syntax issues
    
    You must specify an environment modules: api, admin, public

Perhaps even having 'vern install' run a task which installs all dependencies would be better.

**Comment by jjosef** [comment]
Fixed in version 0.1.39, also you do not have to use `vern install` to install dependencies, you use it to install new packages. Dependencies are installed automatically when you issue a `vern start <env>` command
